# Generated by Django 4.1.7 on 2023-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypointbusiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'managed': True, 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'managed': True, 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': True, 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'managed': True, 'verbose_name_plural': 'Facility types'},
        ),
        migrations.AlterModelOptions(
            name='fareattributes',
            options={'managed': True, 'verbose_name_plural': 'Fare attributes'},
        ),
        migrations.AlterModelOptions(
            name='frequencies',
            options={'managed': True, 'verbose_name_plural': 'frequencies'},
        ),
        migrations.AlterModelOptions(
            name='hasfacilities',
            options={'managed': True, 'verbose_name_plural': 'Has facilities'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'managed': True, 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True, 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='pathways',
            options={'managed': True, 'verbose_name_plural': 'Pathways'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'managed': True, 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='shapes',
            options={'managed': True, 'verbose_name_plural': 'Shapes'},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': True, 'verbose_name_plural': 'Stops'},
        ),
        migrations.AlterModelOptions(
            name='stoptimes',
            options={'managed': True, 'verbose_name_plural': 'Stop times'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'managed': True, 'verbose_name_plural': 'transfers'},
        ),
        migrations.AlterModelOptions(
            name='translations',
            options={'managed': True, 'verbose_name_plural': 'translations'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': True, 'verbose_name_plural': 'trips'},
        ),
        migrations.AlterField(
            model_name='frequencies',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='frequencies',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
