# Generated by Django 4.1.7 on 2023-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypointbusiness', '0002_alter_agency_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rail',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='rail',
            name='route',
        ),
        migrations.AddField(
            model_name='rail',
            name='bus_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rail',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rail',
            name='registration_plate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rail',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rail',
            name='standing_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rail',
            name='unit_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
